# Generated by Django 3.1.2 on 2022-06-19 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("git_hub", models.CharField(max_length=256, verbose_name="github")),
                ("git_flic", models.CharField(max_length=256, verbose_name="gitflic")),
                ("vk", models.CharField(max_length=256, verbose_name="vk")),
                ("email", models.EmailField(max_length=100, verbose_name="почта")),
                (
                    "phone_number",
                    models.CharField(
                        default="1234", max_length=17, verbose_name="номер телефона"
                    ),
                ),
            ],
            options={
                "verbose_name": "контакты",
                "verbose_name_plural": "контакты",
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "edu_type",
                    models.CharField(
                        default="университет",
                        max_length=256,
                        verbose_name="тип образования",
                    ),
                ),
                (
                    "edu_description",
                    models.TextField(verbose_name="описание образования"),
                ),
            ],
            options={
                "verbose_name": "образование",
                "verbose_name_plural": "образование",
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exp_type",
                    models.CharField(
                        default="LMARKT", max_length=200, verbose_name="название опыта"
                    ),
                ),
                (
                    "exp_description",
                    models.TextField(verbose_name="описание опыта работы"),
                ),
            ],
            options={
                "verbose_name": "опыт работы",
                "verbose_name_plural": "опыт работы",
            },
        ),
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill_name",
                    models.CharField(
                        max_length=256, null=True, verbose_name="умения и навыки"
                    ),
                ),
            ],
            options={
                "verbose_name": "умения и навыки",
                "verbose_name_plural": "умения и навыки",
            },
        ),
        migrations.CreateModel(
            name="CandidateInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=150, null=True, verbose_name="полное имя"
                    ),
                ),
                (
                    "contacts",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="api.contacts"
                    ),
                ),
                ("education", models.ManyToManyField(to="api.Education")),
                ("experience", models.ManyToManyField(to="api.Experience")),
                ("skills", models.ManyToManyField(to="api.Skills")),
            ],
            options={
                "verbose_name": "информация о кандидате",
                "verbose_name_plural": "информация о кандидате",
            },
        ),
    ]
