# Generated by Django 3.1.2 on 2022-06-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateinfo",
            name="avatar",
            field=models.TextField(null=True),
        ),
    ]
