# Generated by Django 3.1.2 on 2022-06-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_candidateinfo_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateinfo",
            name="resume_link",
            field=models.TextField(null=True),
        ),
    ]
